version: '3.4'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    ports:
     - "6000:80"

  apimsconsolidado:
    image: ${DOCKER_REGISTRY-}apimsconsolidado
    build:
      context: .
      dockerfile: APIMSConsolidado/Dockerfile
    ports:
     - "6001:80"

  apimslancamentos:
    image: ${DOCKER_REGISTRY-}apimslancamentos
    build:
      context: .
      dockerfile: APIMSLancamentos/Dockerfile
    ports:
     - "6002:80"

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: